# NumPy 

## Using NumPy

In [1]:
import numpy as np

# Numpy Arrays

## Creating NumPy Arrays

### From a Python List

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

In [13]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
### rand

In [16]:
np.random.rand(2)

array([0.82326262, 0.38616581])

In [17]:
np.random.rand(5, 5)

array([[0.8865392 , 0.47927773, 0.43810243, 0.93673136, 0.59462052],
       [0.8866827 , 0.32930218, 0.78973488, 0.74261202, 0.29331163],
       [0.76800656, 0.8133783 , 0.06122132, 0.69804453, 0.64601806],
       [0.80242917, 0.84348134, 0.70578388, 0.11275235, 0.01928225],
       [0.09861266, 0.34402423, 0.9371653 , 0.99051336, 0.37586789]])

### randn

In [18]:
np.random.randn(2)

array([-0.69784707, -0.65138595])

In [19]:
np.random.randn(5, 5)

array([[ 0.03130871,  0.22011345, -1.20423976, -0.67444386,  0.25642491],
       [ 0.44787195, -0.36249756, -0.86152202, -1.15346153, -0.71895424],
       [ 0.10988498, -1.29393476, -0.62431666,  0.47508481,  0.93300647],
       [ 0.01000555,  0.9314095 ,  0.0463462 , -1.44361623,  0.32428013],
       [ 0.37230321, -1.07525695,  0.14334731,  0.66809414, -0.94838548]])

### randint

In [20]:
np.random.randint(1, 100)

21

In [21]:
np.random.randint(1, 100, 10)

array([81,  2,  9, 18,  9, 79,  9, 83, 20,  5])

## Array Attributes and Methods

In [24]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([47, 46,  7, 13,  9, 49, 20, 12, 38,  1])

## Reshape

In [26]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

In [27]:
ranarr

array([47, 46,  7, 13,  9, 49, 20, 12, 38,  1])

In [28]:
ranarr.max()

49

In [29]:
ranarr.argmax()

5

In [30]:
ranarr.min()

1

In [31]:
ranarr.argmin()

9

## Shape

In [35]:
arr.shape

(25,)

In [36]:
type(arr.shape)

tuple

In [41]:
# Notice the two sets of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
type(arr.reshape(1, 25))

numpy.ndarray

In [43]:
arr.reshape(1, 25).shape

(1, 25)

In [44]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Data type of the object in the array

In [46]:
arr.dtype

dtype('int64')